#!/usr/bin/env sh

./gradlew :ejson:clean :ejson:build :ejson:publish $@ --no-daemon --no-parallel && \
./gradlew :gradle-plugin:clean :gradle-plugin:build :gradle-plugin:publish $@ --no-daemon --no-parallel
