name: Publish a release

on:
  push:
    branches:
      - release

env:
  VERSION_FILE: gradle.properties
  VERSION_EXTRACT_PATTERN: '(?<=VERSION_NAME=).+'
  GH_USER_NAME: github.actor

jobs:
  publish_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
        with:
          token: ${{ secrets.PUSH_PAT }}

      - uses: actions/setup-java@a18c333f3f14249953dab3e186e5e21bf3390f1d
        with:
          distribution: 'zulu'
          java-version: 17

      - uses: gradle/wrapper-validation-action@55e685c48d84285a5b0418cd094606e199cca3b6

      - name: Setup Gradle
        uses: gradle/gradle-build-action@3fbe033aaae657f011f88f29be9e65ed26bd29ef
        with:
          gradle-version: wrapper

      - name: Generate versions
        uses: HardNorth/github-version-generate@996e8c5b6ec9cd3e825caf5502d5176238f1109e
        with:
          version-source: file
          version-file: ${{ env.VERSION_FILE }}
          version-file-extraction-pattern: ${{ env.VERSION_EXTRACT_PATTERN }}

      - name: Publish the artifacts
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.ARTIFACT_SIGNING_PRIVATE_KEY }}
          GRADLE_OPTS: -Dorg.gradle.daemon=false -Dkotlin.incremental=false -Dorg.gradle.jvmargs="-Xmx4g -Xms512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -XX:MaxMetaspaceSize=1024m"
        run: ./gradlew publish -PVERSION_NAME=${{ env.RELEASE_VERSION }}

      - name: Create tag
        id: create_tag
        uses: actions/github-script@d556feaca394842dc55e4734bf3bb9f685482fa0
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ env.RELEASE_VERSION }}",
              sha: context.sha
            })

      - name: Build changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@3a70419f3cc01ac7458a4fa44f09726475edfc6a
        with:
          configuration: "changelog_config.json"
          toTag: ${{ env.RELEASE_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release
        id: create_release
        uses: ncipollo/release-action@d9356040b0dc694f6d006b6cabee4d3c024f9e72
        with:
          body: ${{ steps.build_changelog.outputs.changelog }}
          commit: release
          name: Release ${{ env.RELEASE_VERSION }}
          tag: ${{ env.RELEASE_VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
        with:
          ref: 'master'
          token: ${{ secrets.PUSH_PAT }}

      - name: Prepare next dev version
        id: prepare_next_dev
        run: sed -i -e 's/${{ env.CURRENT_VERSION }}/${{ env.NEXT_VERSION }}/g' gradle.properties

      - name: Commit next dev version
        id: commit_next_dev
        uses: EndBug/add-and-commit@d4d066316a2a85974a05efb42be78f897793c6d9
        with:
          add: 'gradle.properties'
          default_author: github_actions
          message: "Prepare next dev version"
